CREATE SEQUENCE IF NOT EXISTS Employee_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS employeephonerelation_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS phone_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE employee
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fio      TEXT                                     NOT NULL,
    address  TEXT,
    position TEXT                                     NOT NULL,
    CONSTRAINT employee_id_pk PRIMARY KEY (id)
);

CREATE TABLE employeephonerelation
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_id    INTEGER                                  NOT NULL,
    employee_id INTEGER                                  NOT NULL,
    CONSTRAINT employeephonerelation_pkey PRIMARY KEY (id)
);

CREATE TABLE phone
(
    number TEXT                                     NOT NULL,
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type   TEXT                                     NOT NULL,
    CONSTRAINT phone_id_pk PRIMARY KEY (id)
);

ALTER TABLE employeephonerelation
    ADD CONSTRAINT employee_id_fk FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE;

CREATE INDEX fki_employee_id_fk ON employeephonerelation (employee_id);

ALTER TABLE employeephonerelation
    ADD CONSTRAINT phone_id_fk FOREIGN KEY (phone_id) REFERENCES phone (id) ON DELETE CASCADE;

CREATE INDEX fki_phone_id_fk ON employeephonerelation (phone_id);